{% set name = "gauche" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gauche-{{ version }}.tar.gz
  sha256: f658523fd24eae2751ff9c86d50c6ef1ab2386402c07030f46028fccfa529791

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - matplotlib-base
    - seaborn
    - jupyterlab
    - ipykernel
    - rdkit
    - tqdm
    - selfies
    - pytorch
    - gpytorch
    - botorch

test:
  imports:
    - gauche
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Gaussian Process Library for Molecules, Chemical Reactions and Proteins.
  home: https://github.com/leojklarner/gauche
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
